// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  $(function($) {
    var $algo, $dist, $progs, $term, algo, defaults, dist, filter, reset_transducer, term, transduce;
    transduce = $.noop;
    $progs = $('textarea.programming-languages');
    defaults = levenshtein.programming_languages.join('\n');
    $term = $('input.query-term');
    $dist = $('select.edit-distance');
    $algo = $('select.algorithm');
    term = '';
    dist = 2;
    algo = 'transposition';
    reset_transducer = function() {
      return transduce = levenshtein.transducer({
        dictionary: levenshtein.programming_languages,
        algorithm: algo,
        sorted: true
      });
    };
    filter = function() {
      var candidates;
      if (term = $.trim($term.val())) {
        candidates = $.map(transduce(term, dist), function(candidate) {
          return candidate[0];
        });
        $progs.val(candidates.join('\n'));
      } else {
        $progs.val(defaults);
      }
      return null;
    };
    $term.keyup(function(event) {
      filter();
      return true;
    });
    $dist.change(function(event) {
      dist = +$dist.find('option:selected').val();
      filter();
      return true;
    });
    $algo.change(function(event) {
      algo = $algo.find('option:selected').val();
      reset_transducer();
      filter();
      return true;
    });
    $dist.val(dist);
    $algo.find("option[value='" + algo + "']").prop('selected', true);
    reset_transducer();
    filter();
    $term.focus();
    return true;
  });

}).call(this);
