// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  $(function($) {
    var $algo, $dist, $progs, $term, algo, builder, defaults, dist, filter, reset_transducer, term, transducer;
    transducer = null;
    $progs = $('textarea.programming-languages');
    defaults = levenshtein.programming_languages.join('\n');
    $term = $('input.query-term');
    $dist = $('select.edit-distance');
    $algo = $('select.algorithm');
    term = '';
    dist = 2;
    algo = 'transposition';
    builder = new levenshtein.Builder().dictionary(levenshtein.programming_languages, true).maximum_candidates(10).include_distance(false).case_insensitive_sort(true).sort_candidates(true);
    reset_transducer = function() {
      return transducer = builder.algorithm(algo).transducer();
    };
    filter = function() {
      var candidates;
      if (term = $.trim($term.val())) {
        candidates = transducer.transduce(term, dist);
        $progs.val(candidates.join('\n'));
      } else {
        $progs.val(defaults);
      }
      return null;
    };
    $term.keyup(function(event) {
      filter();
      return true;
    });
    $dist.change(function(event) {
      dist = +$dist.find('option:selected').val();
      filter();
      return true;
    });
    $algo.change(function(event) {
      algo = $algo.find('option:selected').val();
      reset_transducer();
      filter();
      return true;
    });
    $dist.val(dist);
    $algo.find("option[value='" + algo + "']").prop('selected', true);
    reset_transducer();
    filter();
    $term.focus();
    return true;
  });

}).call(this);
