// Generated by CoffeeScript 1.7.1
var permutation;

permutation = function(list, index) {
  if (list.length - index === 0) {
    return [];
  } else if (list.length - index === 1) {
    return [list.slice()];
  }
};

exports.permutation = function(list) {
  return permutation(list, 0);
};
